# Generated by Django 5.0.9 on 2026-08-01 21:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="SKU interno", max_length=30, unique=True
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("marca", models.CharField(blank=True, max_length=100)),
                (
                    "precio_compra",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("precio_venta", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "porcentaje_isv",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="ISV Honduras: 15% general, 18% bebidas/tabaco, 0% exento",
                        max_digits=5,
                    ),
                ),
                ("stock_minimo", models.PositiveIntegerField(default=0)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Stock",
            },
        ),
        migrations.CreateModel(
            name="TransferenciaInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("abreviatura", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada (compra)"),
                            ("SALIDA", "Salida (venta)"),
                            ("AJUSTE_POS", "Ajuste positivo"),
                            ("AJUSTE_NEG", "Ajuste negativo"),
                            ("TRANS_OUT", "Transferencia - salida"),
                            ("TRANS_IN", "Transferencia - entrada"),
                        ],
                        max_length=15,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Venta #123, Orden de compra #45",
                        max_length=100,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="sucursales.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "ordering": ["-fecha"],
            },
        ),
    ]
