# Generated by Django 5.0.9 on 2026-08-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0003_initial"),
        ("inventario", "0001_initial"),
        ("sucursales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_inventario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="inventario.categoria",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="compras.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="inventario.producto",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="inventario.producto",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="transferenciainventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transferencias",
                to="inventario.producto",
            ),
        ),
        migrations.AddField(
            model_name="transferenciainventario",
            name="sucursal_destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transferencias_entrantes",
                to="sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="transferenciainventario",
            name="sucursal_origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transferencias_salientes",
                to="sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="transferenciainventario",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad_medida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="inventario.unidadmedida",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("producto", "sucursal")},
        ),
    ]
