# Generated by Django 5.0.9 on 2026-08-03 21:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0004_alter_detalleordencompra_cantidad_and_more"),
        ("inventario", "0002_initial"),
        ("sucursales", "0002_alter_sucursal_activa_alter_sucursal_ciudad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="descripción"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=100, unique=True, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="cantidad"
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="motivo",
            field=models.CharField(blank=True, max_length=255, verbose_name="motivo"),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="inventario.producto",
                verbose_name="producto",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Ej: Venta #123, Orden de compra #45",
                max_length=100,
                verbose_name="referencia",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos",
                to="sucursales.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada (compra)"),
                    ("SALIDA", "Salida (venta)"),
                    ("AJUSTE_POS", "Ajuste positivo"),
                    ("AJUSTE_NEG", "Ajuste negativo"),
                    ("TRANS_OUT", "Transferencia - salida"),
                    ("TRANS_IN", "Transferencia - entrada"),
                ],
                max_length=15,
                verbose_name="tipo de movimiento",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_inventario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True, verbose_name="última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="inventario.categoria",
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(
                help_text="SKU interno",
                max_length=30,
                unique=True,
                verbose_name="código",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                verbose_name="código de barras",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos/", verbose_name="imagen"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="marca",
            field=models.CharField(blank=True, max_length=100, verbose_name="marca"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="porcentaje_isv",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="ISV Honduras: 15% general, 18% bebidas/tabaco, 0% exento",
                max_digits=5,
                verbose_name="% ISV",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_compra",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="precio de compra",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="precio de venta"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="proveedor_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="compras.proveedor",
                verbose_name="proveedor principal",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock_minimo",
            field=models.PositiveIntegerField(default=0, verbose_name="stock mínimo"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="inventario.unidadmedida",
                verbose_name="unidad de medida",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True, verbose_name="última actualización"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="cantidad"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="inventario.producto",
                verbose_name="producto",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="sucursales.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="cantidad"
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("COMPLETADA", "Completada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=15,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="fecha_completada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha completada"
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="fecha_solicitud",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transferencias",
                to="inventario.producto",
                verbose_name="producto",
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="sucursal_destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transferencias_entrantes",
                to="sucursales.sucursal",
                verbose_name="sucursal destino",
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="sucursal_origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transferencias_salientes",
                to="sucursales.sucursal",
                verbose_name="sucursal origen",
            ),
        ),
        migrations.AlterField(
            model_name="transferenciainventario",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AlterField(
            model_name="unidadmedida",
            name="abreviatura",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="abreviatura"
            ),
        ),
        migrations.AlterField(
            model_name="unidadmedida",
            name="nombre",
            field=models.CharField(max_length=50, unique=True, verbose_name="nombre"),
        ),
    ]
