# Generated by Django 5.0.9 on 2026-08-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("inventario", "0001_initial"),
        ("sucursales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTA", "Abierta"), ("CERRADA", "Cerrada")],
                        default="ABIERTA",
                        max_length=10,
                    ),
                ),
                (
                    "monto_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monto_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cierres_caja",
                        to="sucursales.sucursal",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cierres_caja",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de caja",
                "verbose_name_plural": "Cierres de caja",
                "ordering": ["-fecha_apertura"],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("CONTADO", "Contado"),
                            ("CREDITO", "Crédito"),
                            ("TARJETA", "Tarjeta"),
                            ("TRANSFERENCIA", "Transferencia bancaria"),
                        ],
                        default="CONTADO",
                        max_length=15,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("COMPLETADA", "Completada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_isv",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = consumidor final",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="sucursales.sucursal",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Se autocompleta con el precio de venta del producto si se deja en 0.",
                        max_digits=12,
                    ),
                ),
                (
                    "porcentaje_isv",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de venta",
                "verbose_name_plural": "Detalles de venta",
            },
        ),
    ]
