# Generated by Django 5.0.9 on 2026-08-03 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_activo_alter_cliente_creado_and_more"),
        (
            "inventario",
            "0003_alter_categoria_descripcion_alter_categoria_nombre_and_more",
        ),
        ("sucursales", "0002_alter_sucursal_activa_alter_sucursal_ciudad_and_more"),
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cierrecaja",
            name="estado",
            field=models.CharField(
                choices=[("ABIERTA", "Abierta"), ("CERRADA", "Cerrada")],
                default="ABIERTA",
                max_length=10,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="fecha_apertura",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de apertura"
            ),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="fecha_cierre",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de cierre"
            ),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="monto_final",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="monto final",
            ),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="monto_inicial",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="monto inicial"
            ),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cierres_caja",
                to="sucursales.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cierres_caja",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="cantidad"
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="descuento"
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="porcentaje_isv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, verbose_name="% ISV"
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="precio_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Se autocompleta con el precio de venta del producto si se deja en 0.",
                max_digits=12,
                verbose_name="precio unitario",
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario.producto",
                verbose_name="producto",
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="ventas.venta",
                verbose_name="venta",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío = consumidor final",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="clientes.cliente",
                verbose_name="cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="descuento"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("COMPLETADA", "Completada"),
                    ("ANULADA", "Anulada"),
                ],
                default="BORRADOR",
                max_length=12,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha_anulacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de anulación"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="forma_pago",
            field=models.CharField(
                choices=[
                    ("CONTADO", "Contado"),
                    ("CREDITO", "Crédito"),
                    ("TARJETA", "Tarjeta"),
                    ("TRANSFERENCIA", "Transferencia bancaria"),
                ],
                default="CONTADO",
                max_length=15,
                verbose_name="forma de pago",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="sucursales.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="total"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total_isv",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ISV total"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vendedor",
            ),
        ),
    ]
