# Generated by Django 5.0.9 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código de establecimiento asignado por SAR, 3 dígitos. Ej: 001",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("es_matriz", models.BooleanField(default=False)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "ordering": ["codigo"],
            },
        ),
    ]
