# Generated by Django 5.0.9 on 2026-08-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sucursal",
            name="activa",
            field=models.BooleanField(default=True, verbose_name="activa"),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, verbose_name="ciudad"),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="codigo",
            field=models.CharField(
                help_text="Código de establecimiento asignado por SAR, 3 dígitos. Ej: 001",
                max_length=3,
                unique=True,
                verbose_name="código",
            ),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="dirección"
            ),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="es_matriz",
            field=models.BooleanField(default=False, verbose_name="es matriz"),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="nombre",
            field=models.CharField(max_length=150, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="teléfono"),
        ),
    ]
