# Generated by Django 5.0.9 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_documento", models.CharField(max_length=30, unique=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("01", "Factura"),
                            ("02", "Nota de crédito"),
                            ("03", "Nota de débito"),
                        ],
                        max_length=2,
                    ),
                ),
                ("rtn_receptor", models.CharField(blank=True, max_length=14)),
                ("nombre_receptor", models.CharField(blank=True, max_length=200)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_isv", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estado",
                    models.CharField(
                        choices=[("EMITIDA", "Emitida"), ("ANULADA", "Anulada")],
                        default="EMITIDA",
                        max_length=10,
                    ),
                ),
                (
                    "codigo_verificacion",
                    models.CharField(
                        blank=True,
                        help_text="Código de verificación del proveedor de facturación electrónica (DTE), si aplica.",
                        max_length=100,
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Documento fiscal",
                "verbose_name_plural": "Documentos fiscales",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=200)),
                ("nombre_comercial", models.CharField(blank=True, max_length=200)),
                (
                    "rtn",
                    models.CharField(
                        help_text="RTN de la empresa (13-14 dígitos)", max_length=14
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresa (configuración fiscal)",
            },
        ),
        migrations.CreateModel(
            name="RangoAutorizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cai",
                    models.CharField(
                        help_text="Código de Autorización de Impresión emitido por el SAR",
                        max_length=50,
                    ),
                ),
                ("punto_emision", models.CharField(default="001", max_length=3)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("01", "Factura"),
                            ("02", "Nota de crédito"),
                            ("03", "Nota de débito"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                ("rango_inicial", models.PositiveIntegerField()),
                ("rango_final", models.PositiveIntegerField()),
                (
                    "numero_actual",
                    models.PositiveIntegerField(
                        help_text="Próximo correlativo a emitir"
                    ),
                ),
                ("fecha_limite_emision", models.DateField()),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Rango autorizado (CAI)",
                "verbose_name_plural": "Rangos autorizados (CAI)",
                "ordering": ["-activo", "sucursal"],
            },
        ),
    ]
