# Generated by Django 5.0.9 on 2026-08-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facturacion", "0001_initial"),
        ("sucursales", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentofiscal",
            name="venta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documento_fiscal",
                to="ventas.venta",
            ),
        ),
        migrations.AddField(
            model_name="rangoautorizado",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rangos_autorizados",
                to="sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="documentofiscal",
            name="rango",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos",
                to="facturacion.rangoautorizado",
            ),
        ),
    ]
