# Generated by Django 5.0.9 on 2026-08-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0002_initial"),
        ("sucursales", "0002_alter_sucursal_activa_alter_sucursal_ciudad_and_more"),
        ("ventas", "0002_alter_cierrecaja_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentofiscal",
            name="codigo_verificacion",
            field=models.CharField(
                blank=True,
                help_text="Código de verificación del proveedor de facturación electrónica (DTE), si aplica.",
                max_length=100,
                verbose_name="código de verificación",
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="estado",
            field=models.CharField(
                choices=[("EMITIDA", "Emitida"), ("ANULADA", "Anulada")],
                default="EMITIDA",
                max_length=10,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="fecha_anulacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de anulación"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="fecha_emision",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de emisión"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="nombre_receptor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="nombre del receptor"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="numero_documento",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="número de documento"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="rango",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos",
                to="facturacion.rangoautorizado",
                verbose_name="rango autorizado",
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="rtn_receptor",
            field=models.CharField(
                blank=True, max_length=14, verbose_name="RTN del receptor"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("01", "Factura"),
                    ("02", "Nota de crédito"),
                    ("03", "Nota de débito"),
                ],
                max_length=2,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="total"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="total_isv",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="ISV total"
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="venta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documento_fiscal",
                to="ventas.venta",
                verbose_name="venta",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="dirección"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre_comercial",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="nombre comercial"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(max_length=200, verbose_name="razón social"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="rtn",
            field=models.CharField(
                help_text="RTN de la empresa (13-14 dígitos)",
                max_length=14,
                verbose_name="RTN",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="teléfono"),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="cai",
            field=models.CharField(
                help_text="Código de Autorización de Impresión emitido por el SAR",
                max_length=50,
                verbose_name="CAI",
            ),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="fecha_limite_emision",
            field=models.DateField(verbose_name="fecha límite de emisión"),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="numero_actual",
            field=models.PositiveIntegerField(
                help_text="Próximo correlativo a emitir", verbose_name="número actual"
            ),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="punto_emision",
            field=models.CharField(
                default="001", max_length=3, verbose_name="punto de emisión"
            ),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="rango_final",
            field=models.PositiveIntegerField(verbose_name="rango final"),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="rango_inicial",
            field=models.PositiveIntegerField(verbose_name="rango inicial"),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rangos_autorizados",
                to="sucursales.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="rangoautorizado",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("01", "Factura"),
                    ("02", "Nota de crédito"),
                    ("03", "Nota de débito"),
                ],
                default="01",
                max_length=2,
                verbose_name="tipo de documento",
            ),
        ),
    ]
