# Generated by Django 5.2.16 on 2026-08-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_barcode_product_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("unidad", "Unidad"),
                    ("par", "Par"),
                    ("docena", "Docena"),
                    ("caja", "Caja"),
                    ("paquete", "Paquete"),
                    ("rollo", "Rollo"),
                    ("metro", "Metro"),
                    ("pie", "Pie"),
                    ("lb", "Libra"),
                    ("kg", "Kilogramo"),
                    ("litro", "Litro"),
                    ("galon", "Galón"),
                    ("saco", "Saco"),
                    ("quintal", "Quintal"),
                ],
                default="unidad",
                max_length=20,
                verbose_name="Unidad de medida",
            ),
        ),
    ]
