# Generated by Django 5.2.16 on 2026-08-04 14:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_purchase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "Compra o gasto",
                "verbose_name_plural": "Compras y gastos",
            },
        ),
        migrations.AddField(
            model_name="purchase",
            name="category",
            field=models.CharField(
                choices=[
                    ("proveedor", "Compra a proveedor (mercadería)"),
                    ("gasto_operativo", "Gasto operativo"),
                    ("acreedor", "Pago a acreedor"),
                ],
                default="proveedor",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Si no tienes registrado al proveedor/acreedor, anota aquí a quién se le pagó.",
                max_length=255,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="No. de factura"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="inventory.provider",
                verbose_name="Proveedor / acreedor",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Subtotal (base gravable)",
            ),
        ),
    ]
