# Generated by Django 5.0.9 on 2026-08-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursales", "0002_alter_sucursal_activa_alter_sucursal_ciudad_and_more"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "usuario", "verbose_name_plural": "usuarios"},
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("GERENTE", "Gerente de sucursal"),
                    ("VENDEDOR", "Vendedor / Cajero"),
                    ("BODEGUERO", "Bodeguero"),
                    ("CONTADOR", "Contador"),
                ],
                default="VENDEDOR",
                max_length=20,
                verbose_name="rol",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal a la que pertenece el usuario. Vacío para administradores globales.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="sucursales.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="teléfono"),
        ),
    ]
