# Generated by Django 5.0.9 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NATURAL", "Persona natural"),
                            ("JURIDICO", "Persona jurídica"),
                        ],
                        default="NATURAL",
                        max_length=10,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo o razón social", max_length=200
                    ),
                ),
                (
                    "rtn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Registro Tributario Nacional (13-14 dígitos). Vacío = consumidor final.",
                        max_length=14,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                (
                    "limite_credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
