# Generated by Django 5.0.9 on 2026-08-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de registro"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="dirección"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="limite_credito",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="límite de crédito",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(
                help_text="Nombre completo o razón social",
                max_length=200,
                verbose_name="nombre",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="rtn",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Registro Tributario Nacional (13-14 dígitos). Vacío = consumidor final.",
                max_length=14,
                verbose_name="RTN",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="teléfono"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NATURAL", "Persona natural"),
                    ("JURIDICO", "Persona jurídica"),
                ],
                default="NATURAL",
                max_length=10,
                verbose_name="tipo de cliente",
            ),
        ),
    ]
