# Generated by Django 5.0.9 on 2026-08-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("inventario", "0001_initial"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleordencompra",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra",
                to="sucursales.sucursal",
            ),
        ),
    ]
