# Generated by Django 5.0.9 on 2026-08-03 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_initial"),
        ("inventario", "0002_initial"),
        ("sucursales", "0002_alter_sucursal_activa_alter_sucursal_ciudad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleordencompra",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="cantidad"
            ),
        ),
        migrations.AlterField(
            model_name="detalleordencompra",
            name="orden",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="compras.ordencompra",
                verbose_name="orden",
            ),
        ),
        migrations.AlterField(
            model_name="detalleordencompra",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=4, max_digits=12, verbose_name="precio unitario"
            ),
        ),
        migrations.AlterField(
            model_name="detalleordencompra",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario.producto",
                verbose_name="producto",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("RECIBIDA", "Recibida"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=15,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="fecha_recepcion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de recepción"
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="notas",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra",
                to="compras.proveedor",
                verbose_name="proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra",
                to="sucursales.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="activo"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="contacto",
            field=models.CharField(blank=True, max_length=150, verbose_name="contacto"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="dirección"
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="rtn",
            field=models.CharField(blank=True, max_length=14, verbose_name="RTN"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="teléfono"),
        ),
    ]
